const INITIAL_STATE = {
  auth: {
    isLoading: false,
    hasError: false,
    error: '',
    isLoggedIn: false,
    adminToken: '',
    user: {
      name: '',
      email: '',
      score: 0,
      balance: 0,
      achivments: [],
      notifications: 0,
      stats: {
        win: 0,
        lose: 0,
        totalWins: 0,
        leaguesPlayed: 0,
      },
    },
  },
  activeLeague: {
    currentLeague: 'Premier League',
    currentLeagueTable: [{
      name: 'Barcelona',
      rank: 1,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'win', 'win', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 2,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'win', 'win', 'draw', 'lose', 'draw'],
    },
    {
      name: 'Barcelona',
      rank: 3,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'lose', 'win', 'draw', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 4,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'draw', 'lose', 'lose', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 5,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['lose', 'draw', 'win', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 5,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 6,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 7,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
    }],
    // Fix dates to be modular
    currentLeagueMatches: [{
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Today',
      time: '20:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      // Fix dates to be modular
      dayName: 'Tommorrow',
      time: '23:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Thu, 13/7',
      time: '21:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Thu, 13/7',
      time: '21:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Thu, 13/7',
      time: '21:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    }],
  },
};

export default INITIAL_STATE;
