import Buffon from '../static/images/profiles/Buffon.png';
import Ronaldo from '../static/images/profiles/Ronaldo.png';
import Neymar from '../static/images/profiles/Neymar.png';
import Messi from '../static/images/profiles/Messi.png';
import Pogba from '../static/images/profiles/Pogba.png';
import Hazard from '../static/images/profiles/Hazard.png';
import Kane from '../static/images/profiles/Kane.png';
import Griezmann from '../static/images/profiles/Griezmann.png';

const INITIAL_STATE = {
  auth: {
    isLoading: false,
    hasError: false,
    error: '',
    isLoggedIn: false,
    adminToken: '',
    user: {
      name: '',
      email: '',
      score: 0,
      balance: 0,
      achivments: [],
      notifications: 0,
      stats: {
        win: 0,
        lose: 0,
        totalWins: 0,
        leaguesPlayed: 0,
      },
    },
  },
  availableMatches: {
    updatedAt: new Date(),
    matches: [{
      league: 'La Liga',
      id: 1,
      homeTeam: 'Barcelona',
      awayTeam: 'Valencia',
      homeOdds: 190,
      awayOdds: 200,
      drawOdds: 100,
      startDate: new Date(2020, 8, 13, 20),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      // This could be 'HT', 'FT', or a minute in the match
      matchTime: 0,
    },
    {
      league: 'La Liga',
      id: 2,
      homeTeam: 'Celta Vigo',
      awayTeam: 'Villareal',
      homeOdds: 55,
      awayOdds: 90,
      drawOdds: 145,
      startDate: new Date(2020, 8, 13, 20),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      matchTime: 0,
    },
    {
      league: 'La Liga',
      id: 3,
      homeTeam: 'Getafe',
      awayTeam: 'Granada',
      homeOdds: 40,
      awayOdds: 140,
      drawOdds: 220,
      startDate: new Date(2020, 8, 13, 22),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      matchTime: 0,
    },
    {
      league: 'Premiere League',
      id: 4,
      homeTeam: 'Liverpool',
      awayTeam: 'Aston Villa',
      homeOdds: 120,
      awayOdds: 100,
      drawOdds: 55,
      startDate: new Date(2020, 8, 13, 22),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      matchTime: 0,
    },
    {
      league: 'Premiere League',
      id: 5,
      homeTeam: 'Manchester United',
      awayTeam: 'Arsenal',
      homeOdds: 110,
      awayOdds: 65,
      drawOdds: 90,
      startDate: new Date(2020, 8, 14, 20),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      matchTime: 0,
    },
    {
      league: 'Premiere League',
      id: 6,
      homeTeam: 'Leicester City',
      awayTeam: 'Manchester City',
      homeOdds: 70,
      awayOdds: 110,
      drawOdds: 185,
      startDate: new Date(2020, 8, 14, 18),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      matchTime: 0,
    },
    {
      league: 'Champions League',
      id: 7,
      homeTeam: 'Barcelona',
      awayTeam: 'Manchester United',
      homeOdds: 30,
      awayOdds: 310,
      drawOdds: 190,
      startDate: new Date(2020, 8, 27, 22),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      matchTime: 0,
    },
    {
      league: 'Champions League',
      id: 8,
      homeTeam: 'Liverpool',
      awayTeam: 'Juventus',
      homeOdds: 70,
      awayOdds: 95,
      drawOdds: 120,
      startDate: new Date(2020, 8, 27, 22),
      isLocked: false,
      homeScore: 0,
      awayScore: 0,
      matchTime: 0,
    }],
  },
  activeTable: {
    name: '',
    description: '',
    players: 0,
    prizePool: 0,
    leagues: [],
    // Type a = all to first, type b = 70 30, type c = 50 30 20
    type: 'a',
    matches: [],
    users: [{
      name: 'Paul Pogba',
      profilePicture: Pogba,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 0,
        awayScore: 2,
      },
      {
        matchId: 2,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 3,
        homeScore: 2,
        awayScore: 0,
      },
      {
        matchId: 4,
        homeScore: 3,
        awayScore: 1,
      },
      {
        matchId: 5,
        homeScore: 5,
        awayScore: 2,
      },
      {
        matchId: 6,
        homeScore: 3,
        awayScore: 2,
      },
      {
        matchId: 7,
        homeScore: 3,
        awayScore: 3,
      },
      {
        matchId: 8,
        homeScore: 1,
        awayScore: 1,
      }],
    },
    {
      name: 'Lionel Messi',
      profilePicture: Messi,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 0,
        awayScore: 2,
      },
      {
        matchId: 2,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 3,
        homeScore: 2,
        awayScore: 0,
      },
      {
        matchId: 4,
        homeScore: 3,
        awayScore: 1,
      },
      {
        matchId: 5,
        homeScore: 5,
        awayScore: 2,
      },
      {
        matchId: 6,
        homeScore: 3,
        awayScore: 2,
      },
      {
        matchId: 7,
        homeScore: 3,
        awayScore: 3,
      },
      {
        matchId: 8,
        homeScore: 1,
        awayScore: 1,
      }],
    },
    {
      name: 'Cristiano Ronaldo',
      profilePicture: Ronaldo,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 1,
        awayScore: 1,
      },
      {
        matchId: 2,
        homeScore: 2,
        awayScore: 3,
      },
      {
        matchId: 3,
        homeScore: 4,
        awayScore: 0,
      },
      {
        matchId: 4,
        homeScore: 3,
        awayScore: 2,
      },
      {
        matchId: 5,
        homeScore: 2,
        awayScore: 2,
      },
      {
        matchId: 6,
        homeScore: 1,
        awayScore: 4,
      },
      {
        matchId: 7,
        homeScore: 3,
        awayScore: 5,
      },
      {
        matchId: 8,
        homeScore: 2,
        awayScore: 0,
      }],
    },
    {
      name: 'Neymar Santos Junior',
      profilePicture: Neymar,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 0,
        awayScore: 2,
      },
      {
        matchId: 2,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 3,
        homeScore: 2,
        awayScore: 0,
      },
      {
        matchId: 4,
        homeScore: 3,
        awayScore: 1,
      },
      {
        matchId: 5,
        homeScore: 5,
        awayScore: 2,
      },
      {
        matchId: 6,
        homeScore: 3,
        awayScore: 2,
      },
      {
        matchId: 7,
        homeScore: 3,
        awayScore: 3,
      },
      {
        matchId: 8,
        homeScore: 1,
        awayScore: 1,
      }],
    },
    {
      name: 'Gianluigi Buffon',
      profilePicture: Buffon,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 2,
        homeScore: 3,
        awayScore: 2,
      },
      {
        matchId: 3,
        homeScore: 2,
        awayScore: 1,
      },
      {
        matchId: 4,
        homeScore: 2,
        awayScore: 1,
      },
      {
        matchId: 5,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 6,
        homeScore: 3,
        awayScore: 3,
      },
      {
        matchId: 7,
        homeScore: 3,
        awayScore: 4,
      },
      {
        matchId: 8,
        homeScore: 2,
        awayScore: 1,
      }],
    },
    {
      name: 'Eden Hazard',
      profilePicture: Hazard,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 0,
        awayScore: 3,
      },
      {
        matchId: 2,
        homeScore: 1,
        awayScore: 3,
      },
      {
        matchId: 3,
        homeScore: 2,
        awayScore: 1,
      },
      {
        matchId: 4,
        homeScore: 1,
        awayScore: 1,
      },
      {
        matchId: 5,
        homeScore: 3,
        awayScore: 2,
      },
      {
        matchId: 6,
        homeScore: 3,
        awayScore: 4,
      },
      {
        matchId: 7,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 8,
        homeScore: 2,
        awayScore: 2,
      }],
    },
    {
      name: 'Harry Kane',
      profilePicture: Kane,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 0,
        awayScore: 1,
      },
      {
        matchId: 2,
        homeScore: 1,
        awayScore: 1,
      },
      {
        matchId: 3,
        homeScore: 2,
        awayScore: 3,
      },
      {
        matchId: 4,
        homeScore: 3,
        awayScore: 4,
      },
      {
        matchId: 5,
        homeScore: 4,
        awayScore: 4,
      },
      {
        matchId: 6,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 7,
        homeScore: 1,
        awayScore: 2,
      },
      {
        matchId: 8,
        homeScore: 1,
        awayScore: 2,
      }],
    },
    {
      name: 'Antoine Griezmann',
      profilePicture: Griezmann,
      currentScore: 0,
      bets: [{
        matchId: 1,
        homeScore: 0,
        awayScore: 3,
      },
      {
        matchId: 2,
        homeScore: 1,
        awayScore: 3,
      },
      {
        matchId: 3,
        homeScore: 2,
        awayScore: 2,
      },
      {
        matchId: 4,
        homeScore: 1,
        awayScore: 1,
      },
      {
        matchId: 5,
        homeScore: 3,
        awayScore: 2,
      },
      {
        matchId: 6,
        homeScore: 2,
        awayScore: 1,
      },
      {
        matchId: 7,
        homeScore: 2,
        awayScore: 0,
      },
      {
        matchId: 8,
        homeScore: 1,
        awayScore: 0,
      }],
    }],
  },
  activeLeague: {
    currentLeague: 'Premier League',
    currentLeagueTable: [{
      name: 'Barcelona',
      rank: 1,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'win', 'win', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 2,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'win', 'win', 'draw', 'lose', 'draw'],
    },
    {
      name: 'Barcelona',
      rank: 3,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'lose', 'win', 'draw', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 4,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['win', 'draw', 'lose', 'lose', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 5,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['lose', 'draw', 'win', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 5,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 6,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
    },
    {
      name: 'Barcelona',
      rank: 7,
      games: 27,
      wins: 18,
      draws: 4,
      loses: 5,
      goals: 63,
      against: 31,
      points: 58,
      lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
    }],
    // Fix dates to be modular
    currentLeagueMatches: [{
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Today',
      time: '20:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      // Fix dates to be modular
      dayName: 'Tommorrow',
      time: '23:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Thu, 13/7',
      time: '21:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Thu, 13/7',
      time: '21:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    },
    {
      homeTeam: 'Valencia',
      awayTeam: 'Levante',
      dayName: 'Thu, 13/7',
      time: '21:00',
      // Use homeOdds, awayOdds, and x Odds here
      homeOdds: 191,
      awayOdds: 40,
      drawOdds: 37.5,
    }],
  },
};

export default INITIAL_STATE;
