// Images
import Liverpool from '../static/images/teams/Barcelona.png';

export const FAKE_TABLES = [{
  players: 3,
  matches: 10,
},
{
  players: 5,
  matches: 10,
},
{
  players: 7,
  matches: 10,
},
{
  players: 10,
  matches: 10,
},
{
  players: 15,
  matches: 10,
},
{
  players: 20,
  matches: 10,
},
{
  players: 30,
  matches: 10,
},
{
  players: 50,
  matches: 10,
}];

export const LA_LIGA_TABLE = [{
  name: 'Barcelona',
  img: Liverpool,
  rank: 1,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'win', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Barcelona',
  img: Liverpool,
  rank: 2,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'win', 'win', 'draw', 'lose', 'draw'],
},
{
  name: 'Barcelona',
  img: Liverpool,
  rank: 3,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'lose', 'win', 'draw', 'lose', 'win'],
},
{
  name: 'Barcelona',
  img: Liverpool,
  rank: 4,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'draw', 'lose', 'lose', 'lose', 'win'],
},
{
  name: 'Barcelona',
  img: Liverpool,
  rank: 5,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['lose', 'draw', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Barcelona',
  img: Liverpool,
  rank: 5,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Barcelona',
  img: Liverpool,
  rank: 6,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Barcelona',
  img: Liverpool,
  rank: 7,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
}];

export const PREMIERE_LEAGUE_TABLE = [{
  name: 'Liverpool',
  img: Liverpool,
  rank: 1,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'win', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Liverpool',
  img: Liverpool,
  rank: 2,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'win', 'win', 'draw', 'lose', 'draw'],
},
{
  name: 'Liverpool',
  img: Liverpool,
  rank: 3,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'lose', 'win', 'draw', 'lose', 'win'],
},
{
  name: 'Liverpool',
  img: Liverpool,
  rank: 4,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'draw', 'lose', 'lose', 'lose', 'win'],
},
{
  name: 'Liverpool',
  img: Liverpool,
  rank: 5,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['lose', 'draw', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Liverpool',
  img: Liverpool,
  rank: 5,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Liverpool',
  img: Liverpool,
  rank: 6,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Liverpool',
  img: Liverpool,
  rank: 7,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
}];
