// Images
import Barcelona from '../static/images/teams/Barcelona.png';
import RealMadrid from '../static/images/teams/RealMadrid.png';
import Sevillia from '../static/images/teams/Sevillia.png';
import Getafe from '../static/images/teams/Getafe.png';
import CeltaVigo from '../static/images/teams/CeltaVigo.png';
import Granada from '../static/images/teams/Granada.png';
import Valencia from '../static/images/teams/Valencia.png';
import Villareal from '../static/images/teams/Villareal.png';
import ManchesterCity from '../static/images/teams/ManchesterCity.png';
import Chelsea from '../static/images/teams/Chelsea.png';
import Tottenham from '../static/images/teams/Tottenham.png';
import ManchesterUnited from '../static/images/teams/ManchesterUnited.png';
import AstonVilla from '../static/images/teams/AstonVilla.png';
import Liverpool from '../static/images/teams/Liverpool.png';
import Arsenal from '../static/images/teams/Arsenal.png';
import Leicester from '../static/images/teams/Leicester.png';

export const FAKE_TABLES = [{
  players: 3,
  matches: 10,
},
{
  players: 5,
  matches: 10,
},
{
  players: 7,
  matches: 10,
},
{
  players: 10,
  matches: 10,
},
{
  players: 15,
  matches: 10,
},
{
  players: 20,
  matches: 10,
},
{
  players: 30,
  matches: 10,
},
{
  players: 50,
  matches: 10,
}];

export const LA_LIGA_TABLE = [{
  name: 'Barcelona',
  img: Barcelona,
  rank: 1,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'win', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Real Madrid',
  img: RealMadrid,
  rank: 2,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['win', 'win', 'win', 'draw', 'lose', 'draw'],
},
{
  name: 'Getafe',
  img: Getafe,
  rank: 3,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'lose', 'win', 'draw', 'lose', 'win'],
},
{
  name: 'Celta Vigo',
  img: CeltaVigo,
  rank: 4,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['win', 'draw', 'lose', 'lose', 'lose', 'win'],
},
{
  name: 'Granada',
  img: Granada,
  rank: 5,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['lose', 'draw', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Valencia',
  img: Valencia,
  rank: 6,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Villareal',
  img: Villareal,
  rank: 7,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Sevillia',
  img: Sevillia,
  rank: 8,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},];

export const PREMIERE_LEAGUE_TABLE = [{
  name: 'Liverpool',
  img: Liverpool,
  rank: 1,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['win', 'win', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Manchester City',
  img: ManchesterCity,
  rank: 2,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'win', 'win', 'draw', 'lose', 'draw'],
},
{
  name: 'Manchester United',
  img: ManchesterUnited,
  rank: 3,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['win', 'lose', 'win', 'draw', 'lose', 'win'],
},
{
  name: 'Aston Villa',
  img: AstonVilla,
  rank: 4,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['win', 'draw', 'lose', 'lose', 'lose', 'win'],
},
{
  name: 'Arsenal',
  img: Arsenal,
  rank: 5,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['lose', 'draw', 'win', 'win', 'lose', 'win'],
},
{
  name: 'Leicester',
  img: Leicester,
  rank: 5,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Tottenham',
  img: Tottenham,
  rank: 6,
  games: 27,
  wins: 18,
  draws: 4,
  loses: 5,
  goals: 63,
  against: 31,
  points: 58,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
},
{
  name: 'Chelsea',
  img: Chelsea,
  rank: 7,
  games: 27,
  wins: 14,
  draws: 7,
  loses: 6,
  goals: 54,
  against: 36,
  points: 49,
  lastSixMatches: ['draw', 'draw', 'lose', 'win', 'lose', 'win'],
}];
